variables:
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  DOCKER_REGISTRY: "$CI_REGISTRY_IMAGE"
  USER: "soaikiba_01"

stages:
  - Debug
  - Prepare
  - Image-Push
  - Test
  - Remove

default:
  interruptible: true
  tags:
    - shell-pc

before_script:
  - chmod -R +wx test/ || exit_code=$?

house-keeping:
    stage: .pre
    variables:
        GIT_CLEAN_FLAGS: -ffdx
        GIT_SUBMODULE_STRATEY: none
    dependencies: []
    script:
        - export CACHE_PATH=/home/$USER/cache/$CI_PROJECT_NAMESPACE
        - export PROJECT_PATH=$CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/$CI_CONCURRENT_ID/$CI_PROJECT_PATH
        - echo $PROJECT_PATH
        - chmod -R +x $PROJECT_PATH
        - rm -rfv $CACHE_PATH/*
        - rm -rfv $PROJECT_PATH/*

debug:
    stage: Debug
    script:
    - echo "Gitlab CI/CD | Print all environment variables"
    - env | sort

prepare:
  stage: Prepare
  retry: 2
  before_script:
    - chmod +x ./vas.sh Makefile
  script:
    - make clean
    - make init
  artifacts:
    when: always 
    expire_in: 1 day
    paths:
      - "build/**/*"

image-push-combined:
  stage: Image-Push
  before_script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin "$CI_REGISTRY"
    - chmod +x ./vas.sh Makefile
    - chmod -R +x build/ || exit_code=$?
    # - rm -rf build/helm-build/**/*.tgz
    # - rm -rf build/helm-build/**/*.sha256
  script:
    - make image
    - make push
    - chmod -R +w build/ || exit_code=$?
  needs:
    - job: prepare

functional-test:
  stage: Test
  before_script:
    - docker images
    - docker ps -a
    - chmod +x ./vas.sh Makefile
  script:
    - make run # Need to run docker container first
    - make test # This for test when docker container is up

remove:
  stage: Remove
  when: always
  before_script:
    - docker images
    - chmod +x ./vas.sh Makefile
  needs:
    - job: image-push-combined
  script:
    - make remove