version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: soai_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=soai_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=soai_user
      - MYSQL_PASSWORD=soai_password
    ports:
      - "3306:3306"
    networks:
      - soai-net
  
  authentication:
    image: authentication:latest
    container_name: soai_authentication
    build:
      context: ./backend/services/authentication
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    environment:
      - DB_HOST=soai_mysql
      - DB_PORT=3306
      - DB_NAME=soai_db
      - DB_USERNAME=soai_user
      - DB_PASSWORD=soai_password
    command: "java -jar app.jar"
    restart: always
    networks:
      - soai-net
    depends_on:
      - mysql

  qdrant:
    image: soai_qdrant:latest
    container_name: soai_qdrant
    build:
      context: ./backend/services/qdrant
      dockerfile: ./Dockerfile
    ports:
      - "6333:6333" # API port
      - "8080:8080" # Web UI (optional)
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__LIMITS__HNSW_MAX_POINTS_PER_INDEX: 1000000
      QDRANT__LIMITS__UPSERT_MAX_POINTS: 1000000
    restart: always
    networks:
      - soai-net
  document:
    image: soai_document:latest
    container_name: soai_document
    build:
      context: ./backend/services/document
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=document-service
      - SERVICE_PORT=8002
    restart: always
    networks:
      - soai-net
    volumes:
      - ./backend/services/document/app:/app
      - uploads:/uploads
  knowledge_base:
    image: soai_knowledge_base:latest
    container_name: soai_knowledge_base
    build:
      context: ./backend/services/knowledge_base
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=knowledge-base-service
      - SERVICE_PORT=8001
    restart: always
    networks:
      - soai-net
    volumes:
      - ./backend/services/knowledge_base/app:/app
  consul:
    image: soai_consul:latest
    container_name: soai_consul
    build:
      context: ./backend/services/consul
      dockerfile: ./Dockerfile
    ports:
      - "8500:8500" # Consul Web UI
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    restart: always
    networks:
      - soai-net
  chatbot:
    container_name: soai_chatbot
    image: soai_chatbot:latest
    build:
      context: ./backend/services/chatbot
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SERVICE_NAME=chatbot-service
      - SERVICE_HOST=chatbot
      - SERVICE_PORT=8000
    restart: always
    networks:
      - soai-net
    volumes:
      - ./backend/services/chatbot/app:/app
      - huggingface:/.cache/huggingface
    depends_on:
      - authentication # For JWT validation
      - consul # For health check
      - ollama # For pulling ollama model

  nginx:
    container_name: soai_nginx
    image: soai_nginx:latest
    build:
      context: ./backend/services/webserver
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - soai-net
    ports:
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/ssl/certs

  ollama:
    image: soai_ollama:latest
    container_name: soai_ollama
    build:
      context: ./backend/services/ollama
    environment:
      - OLLAMA_MODEL_PATH=/home/soai-ollama/.ollama/models
    networks:
      - soai-net
    ports:
      - "11434:11434"
    volumes:
      - ollama:/home/soai-ollama/.ollama:rw
  frontend:
    container_name: soai_frontend
    image: soai_frontend:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    networks:
      - soai-net
    ports:
      - "3000:3000"
    volumes:
      - ./web:/frontend
    command: sh -c "/frontend/loader.sh"
  flowise:
    container_name: soai_flowise
    image: soai_flowise:latest
    build:
      context: ./backend/services/flowise
      dockerfile: ./Dockerfile
    environment:
      - FLOWISE_USERNAME=soai
      - FLOWISE_PASSWORD=soai
    ports:
      - "3003:3000"
    networks:
      - soai-net
  ai_agent:
    container_name: soai_ai_agent
    image: soai_ai_agent:latest
    build:
      context: ./backend/services/ai_agent
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=ai-agent-service
      - SERVICE_PORT=8003
    restart: always
    networks:
      - soai-net
    volumes:
      - ./backend/services/ai_agent/app:/app
  n8n:
    container_name: soai_n8n
    image: soai_n8n:latest
    build:
      context: ./backend/services/n8n
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5678:5678
    networks:
      - soai-net
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  nginx_conf:
  ollama:
  qdrant_data:
  uploads:
  huggingface:
  n8n_data:
networks:
  soai-net:
    driver: bridge
    ipam:
      driver: default
