version: '3.8'

services:
  genai:
    image: soai-gen_ai_provider:latest
    container_name: soai_gen_ai_provider
    build:
      context: ./backend/services/gen_ai_provider
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul:8500
      - SERVICE_NAME=soai_gen_ai_provider
      - SERVICE_PORT=8004
      - OTEL_ENDPOINT=otel-collector:4317
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=DEBUG
    volumes:
      - ./backend/services/gen_ai_provider:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/api/v1/gen-ai/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8004:8004"
    networks:
      - soai-net

  mysql:
    image: bitnami/mysql:8.0.32
    container_name: soai_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=soai_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=soai_user
      - MYSQL_PASSWORD=soai_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - soai-net

  authentication:
    image: soai-authentication:latest
    container_name: soai_authentication
    build:
      context: ./backend/services/authentication
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=soai_mysql
      - DB_PORT=3306
      - DB_NAME=soai_db
      - DB_USERNAME=soai_user
      - DB_PASSWORD=soai_password
    restart: always
    networks:
      - soai-net
    depends_on:
      mysql:
        condition: service_healthy

  consul:
    image: hashicorp/consul:latest
    container_name: soai_consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    restart: always
    networks:
      - soai-net

  web:
    container_name: soai_web
    image: soai-web:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile
    stdin_open: true
    ports:
      - "8080:8080"
    restart: always
    networks:
      - soai-net
    depends_on:
      recruitment:
        condition: service_healthy

  recruitment:
    container_name: soai_recruitment_agent
    image: soai-recruitment_agent:latest
    build:
      context: ./backend/services/recruitment_agent
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul:8500
      - GENAI_HOST=genai:8004
      - SERVICE_NAME=soai_recruitment_agent
      - SERVICE_PORT=8003
      - OTEL_ENDPOINT=otel-collector:4317
      - DB_HOST=soai_mysql
      - DB_PORT=3306
      - DB_NAME=soai_db
      - DB_USERNAME=soai_user
      - LOG_LEVEL=DEBUG
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/api/v1/recruitment/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8003:8003"
    networks:
      - soai-net
    volumes:
      - ./backend/services/recruitment_agent:/app
    depends_on:
      mysql:
        condition: service_healthy
      authentication:
        condition: service_started
      genai:
        condition: service_healthy
      consul:
        condition: service_started
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9091:9090"
    volumes:
      - ./test/observability_config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    networks:
      - soai-net
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./test/observability_config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - soai-net

  clickhouse:
    image: clickhouse:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./test/observability_config/otel-user.xml:/etc/clickhouse-server/users.d/otel-user.xml
      - ./test/observability_config/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: always
    networks:
      - soai-net
volumes:
  clickhouse-data:
networks:
  soai-net:
    driver: bridge
    ipam:
      driver: default
