version: '3.8'

services:
  genai:
    image: soai-gen_ai_provider:latest
    container_name: soai_gen_ai_provider
    build:
      context: ./backend/services/gen_ai_provider
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul:8500
      - SERVICE_NAME=soai_gen_ai_provider
      - SERVICE_PORT=8004
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend/services/gen_ai_provider:/app
    restart: always
    ports:
      - "8004:8004"
    networks:
      - soai-net

  mysql:
    image: mysql:latest
    container_name: soai_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=soai_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=soai_user
      - MYSQL_PASSWORD=soai_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - soai-net

  authentication:
    image: soai-authentication:latest
    container_name: soai_authentication
    build:
      context: ./backend/services/authentication
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DB_HOST=soai_mysql
      - DB_PORT=3306
      - DB_NAME=soai_db
      - DB_USERNAME=soai_user
      - DB_PASSWORD=soai_password
    restart: always
    networks:
      - soai-net
    depends_on:
      mysql:
        condition: service_healthy

  consul:
    image: hashicorp/consul:latest
    container_name: soai_consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    restart: always
    networks:
      - soai-net

  webserver:
    container_name: soai_webserver
    image: soai-webserver:latest
    build:
      context: ./backend/services/webserver
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - soai-net
    ports:
      - "80:80"

  web:
    container_name: soai_web
    image: soai-web:latest
    build:
      context: ./web
      dockerfile: ./Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    networks:
      - soai-net
    volumes:
      - ./web:/frontend
    command: sh -c "/frontend/loader.sh"

  recruitment:
    container_name: soai_recruitment_agent
    image: soai-recruitment_agent:latest
    build:
      context: ./backend/services/recruitment_agent
      dockerfile: ./Dockerfile
    environment:
      - CONSUL_HOST=consul:8500
      - GENAI_HOST=genai:8004
      - SERVICE_NAME=soai_recruitment_agent
      - SERVICE_PORT=8003
      - DB_HOST=soai_mysql
      - DB_PORT=3306
      - DB_NAME=soai_db
      - DB_USERNAME=soai_user
    restart: always
    ports:
      - "8003:8003"
    networks:
      - soai-net
    volumes:
      - ./backend/services/recruitment_agent:/app
    depends_on:
      mysql:
        condition: service_healthy
      authentication:
        condition: service_started
      genai:
        condition: service_started
      consul:
        condition: service_started

networks:
  soai-net:
    driver: bridge
    ipam:
      driver: default