apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.name" . }}
type: Opaque
data:
  admin-username: {{ .Values.grafana.adminUser | b64enc | quote }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}