global:
  security:
    tls:
      enabled: true
otel:
  image: otel/opentelemetry-collector-contrib:latest
  clickHouse:
    enabled: true
  prometheus:
    enabled: true
    scrapeConfigs:
      jobs:
        pod:
          enabled: true
        service:
          enabled: true
        endpoint:
          enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"