{{- $g := fromJson (include "soai-application.global" . ) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "soai-authentication.name" . }}
  labels: {{- include "soai-authentication.labels" . | nindent 4 }}
  annotations: {{- include "soai-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.authentication.replicaCount }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels: 
      {{- include "soai-authentication.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: 
        {{- $appArmorAnn := include "soai-application.appArmorProfileAnnotation" . | fromYaml -}}
        {{- $defaultAnn := include "soai-application.annotations" . | fromYaml -}}
        {{- $annotations := list $appArmorAnn $defaultAnn -}}
        {{- include "soai-application.mergeAnnotations" (dict "location" (.Template.Name) "sources" $annotations) | trim | nindent 8 }}
      labels: 
        {{- include "soai-authentication.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- include "soai-application.appArmorProfile.securityContext" (list .) | indent 8 }}
        fsGroup: {{ template "soai-application.fsGroup.coordinated" . }}
        {{- include "soai-application.podSeccompProfile" . | indent 8 }}
        {{- include "soai-application.supplementalGroups" . }}
      initContainers:
      {{- include "soai-initContainers" (list . "authentication") | indent 6 }}
      {{- include "soai-initContainers" (list . "recruitment") | indent 6 }}
      containers:
      {{- include "soai-auth-containers" (list .) | nindent 6 }}
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: config-properties
        configMap:
          name: {{ template "soai-application.name" . }}-auth-configmap
          defaultMode: 0444
          items:
            - key: application.yaml
              path: application.yaml
      {{- if $g.security.tls.enabled }}
      - name: tls-secret
        secret:
          secretName: {{ template "soai-application.name" . }}-cert
      - name: keystore-cert
        emptyDir: {}
      {{- end }}
    {{- if include "soai-application.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "soai-application.pullSecrets" . }}
    {{- end }}
