apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {{- include "soai-application.annotations" . | nindent 4 }}
  labels: {{- include "soai-mysql.labels" . | nindent 4 }}
  name: {{ template "soai-mysql.name" . }}
spec:
  replicas: {{ .Values.server.mysqlServer.replicaCount }}
  serviceName: {{ .Values.server.mysqlServer.name | quote }}
  selector:
    matchLabels: {{- include "soai-mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- include "soai-application.annotations" . | nindent 8 }}
      labels: {{- include "soai-mysql.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ template "soai-application.fsGroup.coordinated" . }}
        {{- include "soai-application.podSeccompProfile" . | indent 8 }}
        {{- include "soai-application.supplementalGroups" . }}
      initContainers:
      {{- include "ck-initContainers" (list . "mysql") | indent 6 }}
      containers:
      {{- include "soai-mysql.container" (list .) | nindent 6 }}