{{- $g := fromJson (include "soai-application.global" . ) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "soai-qdrant.name" . }}
  labels: {{- include "soai-qdrant.labels" . | nindent 4 }}
  annotations: {{- include "soai-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.qdrant.replicaCount }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels: {{- include "soai-qdrant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- $appArmorAnn := include "soai-application.appArmorProfileAnnotation" . | fromYaml -}}
        {{- $defaultAnn := include "soai-application.annotations" . | fromYaml -}}
        {{- $annotations := list $appArmorAnn $defaultAnn -}}
        {{- include "soai-application.mergeAnnotations" (dict "location" (.Template.Name) "sources" $annotations) | trim | nindent 8 }}
      labels: {{- include "soai-qdrant.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- include "soai-application.appArmorProfile.securityContext" (list .) | indent 8 }}
        fsGroup: 1000
        {{- include "soai-application.podSeccompProfile" . | indent 8 }}
        {{- include "soai-application.supplementalGroups" . }}
      {{- if .Values.storage.enabled }}
      initContainers:
      {{- include "soai-initContainers" (list . "qdrant") | nindent 6 }}
      {{- end }}
      containers:
      {{- include "soai-qdrant-containers" (list .) | nindent 6 }}
      volumes:
      {{- if $g.security.tls.enabled }}
      - name: tls-cert
        secret:
          secretName: {{ template "soai-application.name" . }}-cert
      {{- end }}
      - name: qdrant-storage
        {{- if .Values.storage.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "soai-qdrant.name" . }}-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      # Ephemeral volume for qdrant snapshots
      - name: qdrant-snapshots
        emptyDir: {}
      # Ephemeral volume for qdrant working directory
      - name: qdrant-workdir
        emptyDir: {}
      # Ephemeral volume for qdrant init indicator file
      - name: qdrant-init
        emptyDir: {}
    {{- if include "soai-application.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "soai-application.pullSecrets" . }}
    {{- end }}
