apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "soai-redis.name" . }}
  labels: {{- include "soai-redis.labels" . | nindent 4 }}
  annotations: {{- include "soai-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.redis.replicaCount}}
  strategy:
{{ toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "soai-redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- $defaultAnn := include "soai-application.annotations" . | fromYaml -}}
        {{- $annotations := list $defaultAnn -}}
        {{- include "soai-application.mergeAnnotations" (dict "location" (.Template.Name) "sources" $annotations) | trim | nindent 8 }}
      labels:
        {{- include "soai-redis.labels" . | nindent 8 }}
    spec:
    {{- if include "soai-application.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "soai-application.pullSecrets" . }}
    {{- end }}
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: {{ .Values.server.redis.port }}
          resources:
{{- include "soai-application.resources" (index .Values "resources" "redis") | indent 10 }}