{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.prometheusServiceName" . }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: 9090
    protocol: TCP
    name: web
  selector:
    app: prometheus
---
{{- end }}
{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.nodeExporterServiceName" . }}
spec:
  type: {{ .Values.nodeExporter.service.type }}
  ports:
  - port: {{ .Values.nodeExporter.service.port }}
    targetPort: 9100
    protocol: TCP
    name: metrics
  selector:
    app: node-exporter
---
{{- end }}
{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.alertmanagerServiceName" . }}
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
  - port: {{ .Values.alertmanager.service.port }}
    targetPort: 9093
    protocol: TCP
    name: web
  selector:
    app: alertmanager
{{- end }}
