apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus.name" . }}
spec:
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
