{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
data:
  alert.rules.yml: |
{{ .Files.Get "alert-rules/alert.rules.yml" | indent 4 }}
{{- end }}

