productName: SOAI AI Agent System
images:
  soai-authentication:
    productName: SOAI Authentication API server
    registry: '%%REGISTRY%%'
    name: soai-authentication
    tag: '%%VERSION%%'
  soai-recruitment:
    productName: SOAI Recruitment API server
    registry: '%%REGISTRY%%'
    name: soai-recruitment_agent
    tag: '%%VERSION%%'
  soai-genai:
    productName: SOAI GenAI API server
    registry: '%%REGISTRY%%'
    name: soai-gen_ai_provider
    tag: '%%VERSION%%'
  soai-agent-controller:
    productName: SOAI Agent Controller API server
    registry: '%%REGISTRY%%'
    name: soai-agent_controller
    tag: '%%VERSION%%'
  soai-web:
    productName: SOAI Web
    registry: '%%REGISTRY%%'
    name: soai-web
    tag: '%%VERSION%%'
  soai-mysql:
    productName: SOAI MySQL
    name: mysql
    tag: 9.4.0
  soai-consul:
    productName: SOAI Consul
    registry: 'hashicorp'
    name: consul
    tag: latest