productName: SOAI AI Agent System
images:
  soai-authentication:
    productName: SOAI Authentication API server
    registry: '%%REGISTRY%%'
    name: soai-authentication
    tag: '%%VERSION%%'
  soai-recruitment:
    productName: SOAI Recruitment API server
    registry: '%%REGISTRY%%'
    name: soai-recruitment_agent
    tag: '%%VERSION%%'
  soai-genai:
    productName: SOAI GenAI API server
    registry: '%%REGISTRY%%'
    name: soai-gen_ai_provider
    tag: '%%VERSION%%'
  soai-web:
    productName: SOAI Web
    registry: '%%REGISTRY%%'
    name: soai-web
    tag: '%%VERSION%%'
  soai-mysql:
    productName: SOAI MySQL
    registry: 'bitnami'
    name: mysql
    tag: 8.0.32
  soai-webserver:
    productName: SOAI Web Server
    registry: 'nginxinc'
    name: nginx-unprivileged
    tag: latest